package id.uinjkt.salaamustadz.utils

object Constants {
    const val KEY_IS_FIRST_TIME: String = "isFirstTIme"
    const val KEY_WALKTHROUGH_NAME: String = "walkThrough"
    const val KEY_CHAT_AVAILABLE: String = "chatAvailability"
    const val KEY_SURAH: String = "surah"
    const val KEY_POSITION: String = "position"
    const val KEY_DOA: String = "doa"
    const val KEY_ARTICLE_ID: String = "articleId"
    const val KEY_ARTICLE: String = "article"
    const val KEY_CITY: String = "city"
    const val KEY_COUNTRY: String = "country"
    const val KEY_PRAYER_SCHEDULE: String = "prayerSchedule"
    const val KEY_NOTIFICATION_TYPE_PRAYER: String = "notification_type_prayer"
    const val KEY_NOTIFICATION_TYPE_ARTICLE: String = "notification_type_article"
    const val KEY_NOTIFICATION_TYPE_DZIKIR: String = "notification_type_dzikir"
    const val KEY_NOTIFICATION_TIME: String = "notification_time"
    const val KEY_REMINDERS_ENABLED: String = "reminders_enabled"
    const val KEY_REMINDERS_TIME: String = "reminders_time"
    const val KEY_DZIKIR_ENABLED: String = "dzikir_enabled"
    const val KEY_ARTICLE_ENABLED: String = "article_enabled"
    const val KEY_DZIKIR_TYPE = "key_dzikir_type"

    const val BASE_URL: String = "https://chatappsalamustadz.web.app/api/"
    const val REMOTE_NOTIFICATION_ID: String = "notification_id"
    const val KEY_TYPE_MSG: String = "type_message"
    const val KEY_USTADZ: String = "ustadz"
    const val KEY_USTADZAH: String = "ustadzah"
    const val KEY_ADMIN: String = "admin"
    const val KEY_ADMIN_EMAIL: String = "adminEmail"
    const val KEY_ADMIN_PASSWORD: String = "adminPassword"
    const val KEY_MAN: String = "Laki-Laki"
    const val KEY_USER: String = "user"
    const val KEY_USERS: String = "users"
    const val KEY_ROLE: String = "role"
    const val KEY_IMAGE_MESSAGE: String = "image"
    const val KEY_IMAGE: String = "image"
    const val KEY_NAME_IMAGE_OWNER: String = "name"

    const val KEY_CONSULTATION_REVIEWS: String = "consultation_reviews"
    const val KEY_COLLECTION_USER: String = "users"
    const val KEY_COLLECTION_CHAT_ROOMS: String = "chat_rooms"
    const val KEY_COLLECTION_CHAT: String = "chat"
    const val KEY_SENDER_ID: String = "sender_id"
    const val KEY_RECEIVER_ID: String = "receiver_id"
    const val KEY_CHAT_ROOM_ID: String = "chat_room_id"
    const val KEY_AVAILABILITY: String = "online_status"
    const val KEY_FCM_TOKEN: String = "fcm_token"
    const val KEY_MESSAGE: String = "message"
    const val KEY_CHAT_ID: String = "chat_id"
    const val KEY_NAME: String = "name"
    const val KEY_NOTIFICATION_NAME: String = "notification_name"
    const val KEY_EMAIL: String = "email"
    const val KEY_PASSWORD: String = "password"
    const val KEY_PHONE_NUMBER: String = "phoneNumber"
    const val KEY_URL_SALAAM_USTADZ: String = "urlSalaamUstadz"
    const val KEY_URL_DONATE: String = "urlDonate"
    const val KEY_URL_PRIVACY_POLICY: String = "urlPrivacyPolicy"
    const val KEY_REFERENCE_NAME: String = "chat_app_preference"
    const val KEY_LATEST_VERSION_CODE: String = "latestVersionCodeSalaamUstadz"
    const val KEY_IS_SIGNED_IN = "is_sign_in"
    const val KEY_USER_ID: String = "user_id"
    const val KEY_USER_NAME: String = "user_name"
    const val KEY_MESSAGING_SERVICE: String = "messaging_service"
}