package id.uinjkt.salaamustadz.utils
object Field {
    const val gender: String = "gender"
    const val updatedAt: String = "updatedAt"
    const val createdAt: String = "createdAt"
    const val onChatStatus: String = "onChatStatus"
    const val fcmToken: String = "fcmToken"
    const val onlineStatus: String = "onlineStatus"
    const val lastSeen: String = "lastSeen"
    const val status: String = "status"
    const val fromId: String = "fromId"
    const val chatRoomId: String = "chatRoomId"
    const val id: String = "id"
    const val senderId: String = "senderId"
    const val receiverId: String = "receiverId"
    const val ustadzId: String = "ustadzId"
    const val senderLastMessageNumber: String = "senderLastMessageNumber"
    const val receiverLastMessageNumber: String = "receiverLastMessageNumber"
    const val lastMessageId: String = "lastMessageId"
    const val lastMessageDelStatus: String = "lastMessageDelStatus"
    const val lastMessageReadStatus: String = "lastMessageReadStatus"
    const val chatAvailability: String = "chatAvailability"
    const val endTime: String = "endTime"
    const val endBy: String = "endBy"
    const val delFor: String = "delFor"
    const val delBy: String = "delBy"
    const val unreadCount: String = "unreadCount"
    const val datetime: String = "datetime"
    const val lastText: String = "lastText"
    const val messageNumber: String = "messageNumber"
    const val timestamp: String = "timestamp"
    const val dateAdded: String = "dateAdded"
    const val role: String = "role"
    const val lastTextFrom: String = "lastTextFrom"

}
